platform :ios, '13.0'

target 'WaveMeet' do
  # React Native and its dependencies
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-RCTImage', :path => '../node_modules/react-native/React'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/React'
  pod 'React-RCTText', :path => '../node_modules/react-native/React'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/React'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/React'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/React'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/React'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  # React Native dependencies
  pod 'react-native-vector-icons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-screens', :path => '../node_modules/react-native-screens'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'react-native-gesture-handler', :path => '../node_modules/react-native-gesture-handler'

  # Flipper (optional - for debugging)
  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_os_deployment_target => '10.0',
      :ios_deployment_target => '13.0'
    )
  end
end
